# This action is used to set Expressions to the Face LED Matrix

# GOAL
# Expression to set
cmr_msgs/LEDExpression expression

# Duration in seconds before resetting to normal expression
float32 duration
---
# RESULT

---
# FEEDBACK
